### PR TITLE
[v2] Use first line of outside text as display

### PR DESCRIPTION
**Pull request by Emojigit**
Follow-up of #13 and #14, changes will be made here (WIP)

### CODE REVIEW

**Comment by SamMatzko** [comment]
Hello! Sorry for the lack of clarity, I'll provide the error message I'm getting.

Out of curiosity, what Minetest version are you using? I'm using 5.9.

**Comment by SamMatzko** [comment]
Here is the first error message that shows up:

```
AsyncErr: Lua: Runtime error from mod 'subways_01700_series' in callback environment_Step(): /home/user/.minetest/mods/subways/subways/init.lua:220: bad argument #1 to 'find' (string expected, got nil)
stack traceback:
	[C]: in function 'find'
	/home/user/.minetest/mods/subways/subways/init.lua:220: in function 'update_textures'
	/home/user/.minetest/mods/subways/subways/init.lua:178: in function 'set_textures'
	/home/user/.minetest/mods/advtrains/advtrains/wagons.lua:140: in function 'set_id'
	/home/user/.minetest/mods/advtrains/advtrains/trainlogic.lua:1121: in function 'spawn_wagons'
	/home/user/.minetest/mods/advtrains/advtrains/trainlogic.lua:714: in function 'train_step_c'
	/home/user/.minetest/mods/advtrains/advtrains/trainlogic.lua:114: in function 'mainloop_trainlogic'
	/home/user/.minetest/mods/advtrains/advtrains/init.lua:618: in function </home/user/.minetest/mods/advtrains/advtrains/init.lua:580>
	/usr/share/minetest/builtin/common/register.lua:26: in function </usr/share/minetest/builtin/common/register.lua:12>
```

I can fix this by going to `subways/init.lua` line 20 and changing this:

```lua
local _, _, matched = string.find(self.text_outside, "([^\n]*)\n?.*")
```

to this:

```lua
local _, _, matched = string.find(self.text_outside or "", "([^\n]*)\n?.*")
```

However, once that's fixed, a new error comes up that I unfortunately don't know how to fix:

```
AsyncErr: Lua: Runtime error from mod 'subways_01700_series' in callback luaentity_Step(): /home/user/.minetest/mods/tga_encoder/init.lua:568: attempt to get length of a nil value
stack traceback:
	/home/user/.minetest/mods/tga_encoder/init.lua:568: in function 'encode'
	/home/user/.minetest/mods/subways/subways/init.lua:238: in function 'update_textures'
	/home/user/.minetest/mods/subways/subways/init.lua:153: in function 'custom_on_step'
	/home/user/.minetest/mods/advtrains/advtrains/wagons.lua:313: in function </home/user/.minetest/mods/advtrains/advtrains/wagons.lua:283>
```

**Comment by Emojigit** [comment]
> Out of curiosity, what Minetest version are you using? I'm using 5.9.

On both my computer and the server, I use 5.10.0-dev on Linux.

**Comment by SamMatzko** [comment]
Hmm okay, so that's not the issue. However I think I've discovered what is:

These errors only happen when you have existing subways in your world with the old `line` text, then switch to this fork. Once you've switched to this fork and place a new subway, it works perfectly. So now I understand why it didn't come up during testing lol :P Sorry about that!

**Comment by Emojigit** [comment]
I (hope I've) fixed the problem in the latest commit. Also, I moved the display slot calculation into `if update_text then`.

**Comment by SamMatzko** [comment]
Seems to work well, thank you so much!

**Pull request merged**
